import { pgTable, uuid, varchar, text, timestamp, integer, index, boolean } from 'drizzle-orm/pg-core';
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import { EnumExamType, PgEnumExamType } from './enums.ts';
import { examCategories } from './categories.ts';
import { users } from '../user/users.ts';
import { appTier } from '../app/app-tier.ts';
import { educationGrades } from '../education/education.ts';

/**
 * Table: exam_packages
 * 
 * Defines the final assembled exam/tryout ready to be served to users.
 * This can be an 'official' national tryout generated by an admin, or a 
 * 'custom_practice' instantly generated by a user based on specific tags.
 */
export const examPackages = pgTable('exam_packages', {
    // Unique identifier for the exam bundle
    id: uuid('id').primaryKey().defaultRandom(),

    // Category this exam belongs to
    categoryId: uuid('category_id').references(() => examCategories.id, { onDelete: 'restrict' }).notNull(),

    // Display title representing this exam
    title: varchar('title', { length: 255 }).notNull(),

    // Distinguishes official scheduled exams from ad-hoc custom practices
    examType: PgEnumExamType('exam_type').default(EnumExamType.OFFICIAL).notNull(),

    // If this is a 'custom_practice', link to the user who spawned this session
    createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),

    // Total time allowed to finish this exam
    durationMinutes: integer('duration_minutes').notNull().default(120),

    // Description, rules, or briefing for the tryout
    description: text('description'),

    // Access Gate: Minimum subscription tier required to start this exam
    requiredTier: varchar('required_tier', { length: 50 }).references(() => appTier.slug, { onDelete: 'set null' }).default('free'),

    // Target Audience: The educational level/grade this exam is tailored for
    educationGradeId: integer('education_grade_id').references(() => educationGrades.id, { onDelete: 'set null' }),

    // Control flag to softly hide packages
    isActive: boolean('is_active').default(true).notNull(),

    // Timestamp when this package was created
    createdAt: timestamp('created_at').defaultNow().notNull(),

    // Timestamp when this package was last updated
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (table) => [
    index('exam_packages_category_id_idx').on(table.categoryId),
    index('exam_packages_creator_idx').on(table.createdByUserId),
    index('exam_packages_tier_grade_idx').on(table.requiredTier, table.educationGradeId),
]);

export type SchemaExamPackageSelect = InferSelectModel<typeof examPackages>;
export type SchemaExamPackageInsert = InferInsertModel<typeof examPackages>;
