enum KeyDataType { integer, double, image, fractions, roman, percents, measurement, hours, minutes, clock, text }

enum RandomMode { random, max, range }

enum KeyGroup { grades, topics }

enum KeyTopic {
  topicNumber,
  topicAddition,
  topicSubtraction,
  topicMultiplication,
  topicDivision,
  topicDecimal,
  topicRoot,
  topicExponents,
  topicAlgebra,
  topicRoman,
  topicLength,
  topicWeight,
  topicPrimeFactorization,
  topicClock,
  topicPercents,
  topicFractions,
}

enum KeyChapter {
  numberIntro,
  additionPreSchool,
  additionLine,
  additionSequential,
  addition1Digit,
  addition2Digit,
  addition3Digit,
  addition4Digit,
  additionThreeNumber,
  additionNegative,
  additionMissingDigit,
  additionSimple,
  subtractionPreSchool,
  subtractionLine,
  subtractionSequential,
  subtraction1Digit,
  subtraction2Digit,
  subtraction3Digit,
  subtraction4Digit,
  subtractionThreeNumber,
  subtractionNegative,
  subtractionMissingDigit,
  subtractionSimple,
  multiplicationPreSchool,
  multiplicationLine,
  multiplicationSequential,
  multiplication1Digit,
  multiplication2Digit,
  multiplication3Digit,
  multiplication4Digit,
  multiplicationNegative,
  multiplicationMissingDigit,
  multiplicationSimple,
  divisionPreSchool,
  divisionLine,
  divisionSequential,
  division1Digit,
  division2Digit,
  division3Digit,
  division4Digit,
  divisionNegative,
  divisionMissingDigit,
  divisionSimple,
  romanNumberToRoman,
  romanRomanToNumber,
  romanAddition,
  romanSubtraction,
  percentsUnderstanding,
  percentsOfNumber,
  percentsFromFractions,
  percentsComparison,
  percentsFindTheNumber,
  percentsSolve,
  percentsToFractions,
  lengthConversion,
  lengthAddition,
  lengthSubtraction,
  lengthComparison,
  weightConversion,
  weightAddition,
  weightSubtraction,
  weightComparison,
  fractionsIntroduction,
  fractionsMixedIntroduction,
  fractionsSimplestForm,
  fractionsFromMixed,
  fractionsToMixed,
  fractionsComparison,
  fractionsAddition,
  fractionsSubtraction,
  fractionsMultiplication,
  fractionsDivision,
  factorizationGcf,
  factorizationLcm,
  clockIntroduction,
  clockHoursToMinutes,
  clockMinutesToHours,
  clockElapsedTime,
}

enum KeyGrade {
  gradePre,
  gradeOne,
  gradeTwo,
  gradeThree,
  gradeFour,
  gradeFive,
  gradeSix,
  gradeSeven,
  gradeEight,
  gradeNine,
  gradeTen,
  gradeEleven,
  gradeTwelve,
}

enum KeyPadMode {
  padYesNo,
  pad4Pad,
  padNumPad,
}
