name: 'bse'
description: 'Buku Sekolah Elektronik'
publish_to: 'none'

version: 06.05.21+37

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  drift: ^2.33.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  archive: ^4.0.9
  dio: ^5.9.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_riverpod: ^3.3.1
  shadcn_ui: ^0.54.0
  cached_network_image: ^3.4.1
  syncfusion_flutter_pdfviewer: ^33.2.5
  syncfusion_flutter_charts: ^33.2.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  internet_connection_checker_plus: ^3.0.0
  firebase_crashlytics: ^5.2.2
  firebase_core: ^4.9.0
  flutter_widget_from_html_core: ^0.17.2
  url_launcher: ^6.3.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
  drift_dev: ^2.33.0
  build_runner: ^2.15.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/periodic_dictionary/
